|‼ LOG•DATA	pnum.log
|! System	Windows-10-10.0.19045-SP0
|! Python	3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16)
|! Platform	[MSC v.1940 64 bit (AMD64)]

|= 03/09/2024 18:11:17:687
|> Traceback (most recent call last): → test()
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 35, in main
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 8, in test
|>       x = psequence(Number(k), ..., Number(k * 20e3))
|>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 719, in psequence
|>       return psequence(N[:-1],
|>              ^^^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 738, in psequence
|>       raise ValueError(
|> Er ValueError: Ellipsis cannot be the first element of a sequence.

|= 03/09/2024 18:30:03:260
|> Traceback (most recent call last): → tree = ast.parse(expression, mode='eval')
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2753, in __call__
|>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "C:\Program Files\Python312\Lib\ast.py", line 52, in parse
|>       return compile(source, filename, mode, flags,
|>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "<unknown>", line 1
|>       0.7999...
|>             ^^^
|>   SyntaxError: invalid syntax
|>   
|>   During handling of the above exception, another exception occurred:
|>   
|>   Traceback (most recent call last):
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 278, in pnumber
|>       num = Seval(str(val))
|>             ^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2755, in __call__
|>       raise cls.UnsafeError("Invalid syntax in expression")
|> Er PlainToolsB.SEVAL.UnsafeError: Invalid syntax in expression
|> Traceback (most recent call last): → tree = ast.parse(expression, mode='eval')
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2753, in __call__
|>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "C:\Program Files\Python312\Lib\ast.py", line 52, in parse
|>       return compile(source, filename, mode, flags,
|>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "<unknown>", line 1
|>       0.8999...
|>             ^^^
|>   SyntaxError: invalid syntax
|>   
|>   During handling of the above exception, another exception occurred:
|>   
|>   Traceback (most recent call last):
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 278, in pnumber
|>       num = Seval(str(val))
|>             ^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2755, in __call__
|>       raise cls.UnsafeError("Invalid syntax in expression")
|> Er PlainToolsB.SEVAL.UnsafeError: Invalid syntax in expression
|> Traceback (most recent call last): → tree = ast.parse(expression, mode='eval')
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2753, in __call__
|>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "C:\Program Files\Python312\Lib\ast.py", line 52, in parse
|>       return compile(source, filename, mode, flags,
|>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "<unknown>", line 1
|>       0.999...
|>            ^^^
|>   SyntaxError: invalid syntax
|>   
|>   During handling of the above exception, another exception occurred:
|>   
|>   Traceback (most recent call last):
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 278, in pnumber
|>       num = Seval(str(val))
|>             ^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2755, in __call__
|>       raise cls.UnsafeError("Invalid syntax in expression")
|> Er PlainToolsB.SEVAL.UnsafeError: Invalid syntax in expression
|> Traceback (most recent call last): → tree = ast.parse(expression, mode='eval')
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2753, in __call__
|>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "C:\Program Files\Python312\Lib\ast.py", line 52, in parse
|>       return compile(source, filename, mode, flags,
|>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "<unknown>", line 1
|>       111...
|>            ^
|>   SyntaxError: invalid syntax
|>   
|>   During handling of the above exception, another exception occurred:
|>   
|>   Traceback (most recent call last):
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 278, in pnumber
|>       num = Seval(str(val))
|>             ^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2755, in __call__
|>       raise cls.UnsafeError("Invalid syntax in expression")
|> Er PlainToolsB.SEVAL.UnsafeError: Invalid syntax in expression
|> Traceback (most recent call last): → tree = ast.parse(expression, mode='eval')
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2753, in __call__
|>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "C:\Program Files\Python312\Lib\ast.py", line 52, in parse
|>       return compile(source, filename, mode, flags,
|>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "<unknown>", line 1
|>       111...
|>            ^
|>   SyntaxError: invalid syntax
|>   
|>   During handling of the above exception, another exception occurred:
|>   
|>   Traceback (most recent call last):
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 278, in pnumber
|>       num = Seval(str(val))
|>             ^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2755, in __call__
|>       raise cls.UnsafeError("Invalid syntax in expression")
|> Er PlainToolsB.SEVAL.UnsafeError: Invalid syntax in expression
|> Traceback (most recent call last): → tree = ast.parse(expression, mode='eval')
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2753, in __call__
|>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "C:\Program Files\Python312\Lib\ast.py", line 52, in parse
|>       return compile(source, filename, mode, flags,
|>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "<unknown>", line 1
|>       111...
|>            ^
|>   SyntaxError: invalid syntax
|>   
|>   During handling of the above exception, another exception occurred:
|>   
|>   Traceback (most recent call last):
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 278, in pnumber
|>       num = Seval(str(val))
|>             ^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2755, in __call__
|>       raise cls.UnsafeError("Invalid syntax in expression")
|> Er PlainToolsB.SEVAL.UnsafeError: Invalid syntax in expression
|> Traceback (most recent call last): → tree = ast.parse(expression, mode='eval')
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2753, in __call__
|>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "C:\Program Files\Python312\Lib\ast.py", line 52, in parse
|>       return compile(source, filename, mode, flags,
|>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "<unknown>", line 1
|>       111...
|>            ^
|>   SyntaxError: invalid syntax
|>   
|>   During handling of the above exception, another exception occurred:
|>   
|>   Traceback (most recent call last):
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 278, in pnumber
|>       num = Seval(str(val))
|>             ^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2755, in __call__
|>       raise cls.UnsafeError("Invalid syntax in expression")
|> Er PlainToolsB.SEVAL.UnsafeError: Invalid syntax in expression
|> Traceback (most recent call last): → tree = ast.parse(expression, mode='eval')
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2753, in __call__
|>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "C:\Program Files\Python312\Lib\ast.py", line 52, in parse
|>       return compile(source, filename, mode, flags,
|>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "<unknown>", line 1
|>       111...
|>            ^
|>   SyntaxError: invalid syntax
|>   
|>   During handling of the above exception, another exception occurred:
|>   
|>   Traceback (most recent call last):
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 278, in pnumber
|>       num = Seval(str(val))
|>             ^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2755, in __call__
|>       raise cls.UnsafeError("Invalid syntax in expression")
|> Er PlainToolsB.SEVAL.UnsafeError: Invalid syntax in expression
|> Traceback (most recent call last): → tree = ast.parse(expression, mode='eval')
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2753, in __call__
|>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "C:\Program Files\Python312\Lib\ast.py", line 52, in parse
|>       return compile(source, filename, mode, flags,
|>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "<unknown>", line 1
|>       111...
|>            ^
|>   SyntaxError: invalid syntax
|>   
|>   During handling of the above exception, another exception occurred:
|>   
|>   Traceback (most recent call last):
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 278, in pnumber
|>       num = Seval(str(val))
|>             ^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2755, in __call__
|>       raise cls.UnsafeError("Invalid syntax in expression")
|> Er PlainToolsB.SEVAL.UnsafeError: Invalid syntax in expression
|> Traceback (most recent call last): → tree = ast.parse(expression, mode='eval')
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2753, in __call__
|>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "C:\Program Files\Python312\Lib\ast.py", line 52, in parse
|>       return compile(source, filename, mode, flags,
|>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "<unknown>", line 1
|>       111...
|>            ^
|>   SyntaxError: invalid syntax
|>   
|>   During handling of the above exception, another exception occurred:
|>   
|>   Traceback (most recent call last):
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 278, in pnumber
|>       num = Seval(str(val))
|>             ^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2755, in __call__
|>       raise cls.UnsafeError("Invalid syntax in expression")
|> Er PlainToolsB.SEVAL.UnsafeError: Invalid syntax in expression
|> Traceback (most recent call last): → tree = ast.parse(expression, mode='eval')
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2753, in __call__
|>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "C:\Program Files\Python312\Lib\ast.py", line 52, in parse
|>       return compile(source, filename, mode, flags,
|>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "<unknown>", line 1
|>       111...
|>            ^
|>   SyntaxError: invalid syntax
|>   
|>   During handling of the above exception, another exception occurred:
|>   
|>   Traceback (most recent call last):
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 278, in pnumber
|>       num = Seval(str(val))
|>             ^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2755, in __call__
|>       raise cls.UnsafeError("Invalid syntax in expression")
|> Er PlainToolsB.SEVAL.UnsafeError: Invalid syntax in expression
|> Traceback (most recent call last): → tree = ast.parse(expression, mode='eval')
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2753, in __call__
|>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "C:\Program Files\Python312\Lib\ast.py", line 52, in parse
|>       return compile(source, filename, mode, flags,
|>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "<unknown>", line 1
|>       111...
|>            ^
|>   SyntaxError: invalid syntax
|>   
|>   During handling of the above exception, another exception occurred:
|>   
|>   Traceback (most recent call last):
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 278, in pnumber
|>       num = Seval(str(val))
|>             ^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2755, in __call__
|>       raise cls.UnsafeError("Invalid syntax in expression")
|> Er PlainToolsB.SEVAL.UnsafeError: Invalid syntax in expression
|> Traceback (most recent call last): → for i in x:
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 12, in test
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 748, in <genexpr>
|>       L.append(pnumber(x) for x in itertools.takewhile(
|>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 750, in <lambda>
|>       x <= limit or abs(x - limit) < S / 10),
|>                     ^^^^^^^^^^^^^^
|> Er TypeError: abs() missing 1 required positional argument: 'other'

|= 03/09/2024 18:52:07:560
|> Traceback (most recent call last): → psequence(1, 2, 3, ..., 10)
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 33, in main
|>         ^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 8, in test
|>       """
|>           
|> Er ValueError: could not convert string to float: 'python -u "c:\\Users\\Gabriel\\Documents\\GitHub\\PlainTools\\works\\Block.py"'

|= 03/09/2024 18:59:53:171
|> Traceback (most recent call last): → tree = ast.parse(expression, mode='eval')
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2680, in __call__
|>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "C:\Program Files\Python312\Lib\ast.py", line 52, in parse
|>       return compile(source, filename, mode, flags,
|>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "<unknown>", line 1
|>       0.7999...
|>             ^^^
|>   SyntaxError: invalid syntax
|>   
|>   During handling of the above exception, another exception occurred:
|>   
|>   Traceback (most recent call last):
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 11, in test
|>       for i in x:
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 673, in <genexpr>
|>       L.append(pnumber(x) for x in itertools.takewhile(
|>                ^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 259, in pnumber
|>       R.append(round(Number(Seval(str(num)), tol=tol), dcm))
|>                             ^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 2682, in __call__
|>       raise cls.UnsafeError("Invalid syntax in expression")
|> Er PlainToolsB.SEVAL.UnsafeError: Invalid syntax in expression

|= 03/09/2024 19:01:15:104
|> Traceback (most recent call last): → test(ip)
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 35, in main
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 7, in test
|>       x = psequence(Number(k), ..., Number(k * 20e3))
|>                     ^^^^^^^^^
|> Er ValueError: could not convert string to float: 'python -u "c:\\Users\\Gabriel\\Documents\\GitHub\\PlainTools\\works\\pnum.py"'

|= 03/09/2024 19:03:03:830
|> Traceback (most recent call last): → for i in x:
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 11, in test
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 673, in <genexpr>
|>       L.append(pnumber(x) for x in itertools.takewhile(
|>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 675, in <lambda>
|>       x <= limit or abs(x - limit) < S / 10),
|>                     ^^^^^^^^^^^^^^
|> Er TypeError: abs() missing 1 required positional argument: 'other'

|= 03/09/2024 19:07:25:532
|> Traceback (most recent call last): → test(ip)
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 35, in main
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 7, in test
|>       x = psequence(Number(k), ..., Number(k * 20e3))
|>                     ^^^^^^^^^
|> Er ValueError: could not convert string to float: 'python -u "c:\\Users\\Gabriel\\Documents\\GitHub\\PlainTools\\works\\pnum.py"'

|= 03/09/2024 19:14:02:210
|> Traceback (most recent call last): → tol = RT(abs(num))
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 3210, in number
|>           ^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 3190, in RT
|>       def RT(x): return max(4, 16 - math.ceil(math.log(
|>                                               ^^^^^^^^^
|> Er ZeroDivisionError: float division by zero
|> Traceback (most recent call last): → test()
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 38, in main
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 7, in test
|>       x = psequence(Number(k), ..., Number(k * 20e3))
|>                     ^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 3160, in __init__
|>       cls.fraction = cls.value.as_integer_ratio()
|>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
|> Er AttributeError: 'NoneType' object has no attribute 'as_integer_ratio'

|= 03/09/2024 19:14:08:122
|> Traceback (most recent call last): → tol = RT(abs(num))
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 3210, in number
|>           ^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 3190, in RT
|>       def RT(x): return max(4, 16 - math.ceil(math.log(
|>                                               ^^^^^^^^^
|> Er ZeroDivisionError: float division by zero
|> Traceback (most recent call last): → test()
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 38, in main
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 7, in test
|>       x = psequence(Number(k), ..., Number(k * 20e3))
|>                     ^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 3160, in __init__
|>       cls.fraction = cls.value.as_integer_ratio()
|>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
|> Er AttributeError: 'NoneType' object has no attribute 'as_integer_ratio'

|= 03/09/2024 19:18:54:658
|> Traceback (most recent call last): → for length in range(1, len(dnum) // 4 + 1):
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 3233, in number
|>                            ^^^^^^^^^
|> Er TypeError: object of type 'float' has no len()
|> Traceback (most recent call last): → test()
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 38, in main
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 7, in test
|>       x = psequence(Number(k), ..., Number(k * 20e3))
|>                     ^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 3160, in __init__
|>       cls.fraction = cls.value.as_integer_ratio()
|>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
|> Er AttributeError: 'NoneType' object has no attribute 'as_integer_ratio'

|= 03/09/2024 19:18:56:692
|> Traceback (most recent call last): → for length in range(1, len(dnum) // 4 + 1):
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 3233, in number
|>                            ^^^^^^^^^
|> Er TypeError: object of type 'float' has no len()
|> Traceback (most recent call last): → test()
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 38, in main
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 7, in test
|>       x = psequence(Number(k), ..., Number(k * 20e3))
|>                     ^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 3160, in __init__
|>       cls.fraction = cls.value.as_integer_ratio()
|>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
|> Er AttributeError: 'NoneType' object has no attribute 'as_integer_ratio'

|= 17/09/2024 15:58:08:567
|> Traceback (most recent call last): → test()
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 38, in main
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 7, in test
|>       x = psequence(Number(k), ..., Number(k * 20e3))
|>                     ^^^^^^^^^
|> Er TypeError: Number() takes no arguments

|= 17/09/2024 16:04:09:431
|> Traceback (most recent call last): → test(ip)
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 34, in main
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 6, in test
|>       x = psequence(k, k * 2, ..., k * 20e3)
|>                                    ~~^~~~~~
|> Er TypeError: can't multiply sequence by non-int of type 'float'

|= 17/09/2024 16:05:37:345
|> Traceback (most recent call last): → test(ip)
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 34, in main
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 6, in test
|>       x = psequence(k)
|>           ^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 849, in psequence
|>       return psequence(N[0], ...,
|>              ^^^^^^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 865, in psequence
|>       limit = number(N[-2] * rel_lim) if N[-1] == ... else number(
|>                      ~~~~~~^~~~~~~~~
|> Er TypeError: can't multiply sequence by non-int of type 'float'

|= 17/09/2024 16:06:22:435
|> Traceback (most recent call last): → test(ip)
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 35, in main
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 6, in test
|>       x = psequence(k)
|>           ^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 849, in psequence
|>       return psequence(N[0], ...,
|>              ^^^^^^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 865, in psequence
|>       limit = number(N[-2] * rel_lim) if N[-1] == ... else number(
|>                      ~~~~~~^~~~~~~~~
|> Er TypeError: can't multiply sequence by non-int of type 'float'

|= 17/09/2024 16:06:34:257
|> Traceback (most recent call last): → test(ip)
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 36, in main
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 6, in test
|>       x = psequence(k)
|>           ^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 849, in psequence
|>       return psequence(N[0], ...,
|>              ^^^^^^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 865, in psequence
|>       limit = number(N[-2] * rel_lim) if N[-1] == ... else number(
|>                      ~~~~~~^~~~~~~~~
|> Er TypeError: can't multiply sequence by non-int of type 'float'

|= 17/09/2024 16:07:32:525
|> Traceback (most recent call last): → test(ip)
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 35, in main
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 5, in test
|>       x = ptb.psequence(k)
|>           ^^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 849, in psequence
|>       return psequence(N[0], ...,
|>              ^^^^^^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 865, in psequence
|>       limit = number(N[-2] * rel_lim) if N[-1] == ... else number(
|>                      ~~~~~~^~~~~~~~~
|> Er TypeError: can't multiply sequence by non-int of type 'float'

|= 17/09/2024 16:08:04:221
|> Traceback (most recent call last): → test(ip)
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 33, in main
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 5, in test
|>       x = ptb.psequence(k)
|>           ^^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 849, in psequence
|>       return psequence(N[0], ...,
|>              ^^^^^^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 865, in psequence
|>       limit = number(N[-2] * rel_lim) if N[-1] == ... else number(
|>                      ~~~~~~^~~~~~~~~
|> Er TypeError: can't multiply sequence by non-int of type 'float'

|= 17/09/2024 16:44:22:762
|> Traceback (most recent call last): → if tol == 'auto':
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 517, in pround
|>        ^^^
|> Er UnboundLocalError: cannot access local variable 'tol' where it is not associated with a value
|> Traceback (most recent call last): → raise ArithmeticError(
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 11, in test
|> Er ArithmeticError: NaN | None is present in the sequence.
|> Traceback (most recent call last): → test(ip or 10e-2)
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 35, in main
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 28, in test
|>       print(f'Ratio: {ptb.number(w / (c or 1))}')
|>                       ^^^^^^^^^^
|> Er AttributeError: module 'PlainToolsB' has no attribute 'number'. Did you mean: 'Number'?

|= 17/09/2024 16:44:33:327
|> Traceback (most recent call last): → if tol == 'auto':
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 517, in pround
|>        ^^^
|> Er UnboundLocalError: cannot access local variable 'tol' where it is not associated with a value
|> Traceback (most recent call last): → raise ArithmeticError(
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 11, in test
|> Er ArithmeticError: NaN | None is present in the sequence.

|= 17/09/2024 16:45:24:312
|> Traceback (most recent call last): → if tol == 'auto':
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 517, in pround
|>        ^^^
|> Er UnboundLocalError: cannot access local variable 'tol' where it is not associated with a value
|> Traceback (most recent call last): → raise ArithmeticError(
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 11, in test
|> Er ArithmeticError: NaN | None is present in the sequence.

|= 17/09/2024 16:46:07:094
|> Traceback (most recent call last): → if tol == 'auto':
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 517, in pround
|>        ^^^
|> Er UnboundLocalError: cannot access local variable 'tol' where it is not associated with a value
|> Traceback (most recent call last): → raise ArithmeticError(
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 11, in test
|> Er ArithmeticError: NaN | None is present in the sequence.

|= 17/09/2024 16:47:44:507
|> Traceback (most recent call last): → if tol == 'auto':
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 517, in pround
|>        ^^^
|> Er UnboundLocalError: cannot access local variable 'tol' where it is not associated with a value
|> Traceback (most recent call last): → if tol == 'auto':
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 517, in pround
|>        ^^^
|> Er UnboundLocalError: cannot access local variable 'tol' where it is not associated with a value
|> Traceback (most recent call last): → test(ip or 10e-2)
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 35, in main
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 5, in test
|>       x = ptb.psequence(k, ..., k * 20e3)
|>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 950, in psequence
|>       return psequence(N[:-1],
|>              ^^^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 983, in psequence
|>       itertools.count(start + S, S)))
|>                       ~~~~~~^~~
|> Er TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

|= 17/09/2024 16:48:07:945
|> Traceback (most recent call last): → if tol == 'auto':
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 517, in pround
|>        ^^^
|> Er UnboundLocalError: cannot access local variable 'tol' where it is not associated with a value
|> Traceback (most recent call last): → if tol == 'auto':
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 517, in pround
|>        ^^^
|> Er UnboundLocalError: cannot access local variable 'tol' where it is not associated with a value
|> Traceback (most recent call last): → test(ip or 10e-2)
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 35, in main
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 5, in test
|>       x = ptb.psequence(k, ..., k * 20e3)
|>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 950, in psequence
|>       return psequence(N[:-1],
|>              ^^^^^^^^^^^^^^^^^
|>     File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 984, in psequence
|>       itertools.count(start + S, S)))
|>                       ~~~~~~^~~
|> Er TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

|= 17/09/2024 16:48:36:812
|> Traceback (most recent call last): → if tol == 'auto':
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\PlainToolsB.py", line 517, in pround
|>        ^^^
|> Er UnboundLocalError: cannot access local variable 'tol' where it is not associated with a value
|> Traceback (most recent call last): → raise ArithmeticError(
|>   File "c:\Users\Gabriel\Documents\GitHub\PlainTools\works\pnum.py", line 11, in test
|> Er ArithmeticError: NaN | None is present in the sequence.

